[package]
name = "cargo-wgsl"
version = "0.0.1"
authors = ["Poly <marynczak.bartlomiej@gmail.com>"]
edition = "2018"

[dependencies]
colored = "2.0.0"
naga = {version="0.3.1",features = ["wgsl-in"]}
walkdir = "2.3.1"
