[package]
name = "cargo-wgsl"
version = "0.0.3"
authors = ["Poly <marynczak.bartlomiej@gmail.com>"]
edition = "2018"

description = "Validate wgsl in rust projects"
keywords = ["CLI", "wgsl", "cargo"]
license = "MIT"
repository = "https://github.com/PolyMeilex/cargo-wgsl"

[dependencies]
colored = "2.0"
walkdir = "2.3"
serde = { version = "1.0", features = ["derive"] }
jsonrpc-stdio-server = "17.0"
tokio = { version = "0.2", features = ["rt-core"] }

[dependencies.naga]
git = "https://github.com/gfx-rs/naga"
tag = "gfx-23"
features = ["wgsl-in"]
